language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"

# command to install dependencies
#  install: "pip install -r requirements.txt"

# skip install
install: true

# command to run tests
script: nosetests
